### ISSUE TITLE
抓取之后无法生成规则文件

### ISSUE THREAD

**Issue by catseie** [oooldtoy/SSTAP_ip_crawl_tool#6]
发现RiotClientServices.exe新ip
23.37.126.48
发现新ip203.208.50.56--udp
发现新ip203.208.40.127--udp
发现新ip203.208.41.88--udp
Traceback (most recent call last):
  File "ip_crawl_toolV3.3.4.py", line 173, in <module>
  File "ip_crawl_toolV3.3.4.py", line 170, in main
  File "ip_crawl_toolV3.3.4.py", line 92, in run
  File "udp.py", line 32, in udp_crawl
IndexError: list index out of range
[12876] Failed to execute script ip_crawl_toolV3.3.4

**Comment by catseie** [comment]
对了，没有开启SSTAP，直接抓取的，开启udp

**Comment by oooldtoy** [comment]
@HI2Shawn 多试几次可能会有用。目前正在修复这个bug

**Comment by catseie** [comment]
好的，谢谢
